"""Initial migration

Revision ID: 0ea62e185adc
Revises: 
Create Date: 2024-11-29 12:02:43.241385

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0ea62e185adc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_locations',
    sa.Column('delivery_location_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('customer_location', geoalchemy2.types.Geometry(geometry_type='POINT', spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, _spatial_index_reflected=True), nullable=False),
    sa.Column('estimated_delivery_time', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], name='delivery_locations_ibfk_1'),
    sa.PrimaryKeyConstraint('delivery_location_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('menus',
    sa.Column('menu_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('restaurant_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('menu_data', mysql.JSON(), nullable=False),
    sa.Column('availability_status', mysql.ENUM('Available', 'Not Available'), server_default=sa.text("'Available'"), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.restaurant_id'], name='menus_ibfk_1'),
    sa.PrimaryKeyConstraint('menu_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('customers',
    sa.Column('customer_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('address', mysql.TEXT(), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, _spatial_index_reflected=True), nullable=False),
    sa.PrimaryKeyConstraint('customer_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('promotions',
    sa.Column('promotion_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('promo_code', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('discount_type', mysql.ENUM('Percentage', 'Fixed Amount'), nullable=True),
    sa.Column('discount_value', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('start_date', sa.DATE(), nullable=True),
    sa.Column('end_date', sa.DATE(), nullable=True),
    sa.Column('applicable_restaurants', mysql.JSON(), nullable=True),
    sa.Column('min_order_value', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('usage_limit', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('current_usage', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('promotion_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('promotions', schema=None) as batch_op:
        batch_op.create_index('promo_code', ['promo_code'], unique=True)

    op.create_table('restaurants',
    sa.Column('restaurant_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('address', mysql.TEXT(), nullable=False),
    sa.Column('contact_number', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('rating', mysql.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('opening_hours', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('delivery_area', geoalchemy2.types.Geometry(spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, _spatial_index_reflected=True), nullable=False),
    sa.PrimaryKeyConstraint('restaurant_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('drivers',
    sa.Column('driver_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('contact', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('current_location', geoalchemy2.types.Geometry(geometry_type='POINT', spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True), nullable=True),
    sa.Column('availability_status', mysql.ENUM('Available', 'Unavailable'), server_default=sa.text("'Available'"), nullable=True),
    sa.Column('vehicle_details', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('driver_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('orders',
    sa.Column('order_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('customer_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('restaurant_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order_details', mysql.JSON(), nullable=False),
    sa.Column('order_status', mysql.ENUM('Preparing', 'On the Way', 'Delivered'), server_default=sa.text("'Preparing'"), nullable=True),
    sa.Column('timestamps', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], name='orders_ibfk_1'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.restaurant_id'], name='orders_ibfk_2'),
    sa.PrimaryKeyConstraint('order_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('payments',
    sa.Column('payment_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('customer_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('payment_method', mysql.ENUM('Credit Card', 'Cash'), nullable=False),
    sa.Column('payment_status', mysql.ENUM('Paid', 'Pending', 'Failed'), server_default=sa.text("'Pending'"), nullable=True),
    sa.Column('timestamp', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], name='payments_ibfk_2'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], name='payments_ibfk_1'),
    sa.PrimaryKeyConstraint('payment_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
